apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-5zpk
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0028-tenant/ci1t-830-0028-app/devfile-sample-5zpk@sha256:2a22077ebb330c9dd78c2241b4b1124b6d978e90c90a0bcebaa404c7e25ccf09
        name: my-nodejs
        resources: {}
status: {}
